index:
    path: /
    controller: App\Controller\DefaultController::index
consultation_list:
    path: /consultation/
    controller:  App\Controller\ConsultationController::index
medecin_list:
    path: /medecin/
    controller:  App\Controller\MedecinController::index
medecin_consultation:
    path: /medecin/{id}/consultation
    controller: App\Controller\MedecinController::consultation
medecin_consultation_month:
    path: /medecin/{id}/consultation/{month}/{year}
    controller: App\Controller\MedecinController::consultation
patient_list:
    path: /patient/
    controller:  App\Controller\PatientController::index
medicament_list:
    path: /medicament/
    controller:  App\Controller\MedicamentController::index
users_list:
    path: /admin/users/
    controller: App\Controller\UsersController:index
app_logout:
    path: /logout
    methods: GET